### ISSUE TITLE
Release 3.0.0 broke the compatibility with UWP apps

### ISSUE THREAD

**Issue by prakashutoledo** [robertvazan/guerrillantp#10]
I have a UWP application (a minimum target to `uap10.0.19041`) that uses the 2.0.1 version targeted to netstandard2.0 but updating to the latest version `3.0.0` makes it incompatible with UWP apps

**Comment by robertvazan** [comment]
The new APIs will not work on .NET Standard 2.0 without a lot of effort. UWP is dead anyway, AFAICT. To solve your problem, start a background thread when your application launches and use the sync API in version 2.0.1.

**Comment by tipa** [comment]
Sad to hear I will now too be stuck with an outdated version. 2.0.1 works perfectly fine, no doubt about that. But new features (like LastCorrectionOffset) will now not be available to UWP developers. Plus I will continue to see an item in the NuGet update screen that I cannot get rid of.
I have a whole bunch of UWP apps (with most of them using this library) in the Store and I am still actively working on them. For me, it's the best choice for Desktop apps as WinUI3 still is lacking features (MapView) and is slow (no AOT). So at least for me, UWP is not dead at all. The recently launched new Microsoft Store app is a pure UWP app!
This is the first library (from many that I use) that drops support for UWP.

May I ask what exactly is preventing the library to be compatible with UWP?

**Comment by robertvazan** [comment]
I tried to switch back to .NET Standard 2.0 and got errors all over the place even with `<LangVersion>latest</LangVersion>`: spans, `BinaryPrimitives`, records (init-only properties), cancellable async overloads.

2.0.1 is fine. Aside from async, you really lose only some convenience.

**Comment by prakashutoledo** [comment]
> The new APIs will not work on .NET Standard 2.0 without a lot of effort. UWP is dead anyway, AFAICT. To solve your problem, start a background thread when your application launches and use the sync API in version 2.0.1.

That's what I have been doing running `GetCorrectionOffset` in Task.Run and awaiting the task returning from it. It's really sad to see to drop support for UWP apps all of sudden but 2.0.1 works all fine even without async support. Anyway thanks so much
