### ISSUE TITLE
[Feature Request] Work in Unity 2021.3 and above

### ISSUE THREAD

**Issue by ApprenticeGC** [robertvazan/guerrillantp#11]
This is not an issue but rather a feature request.

Tried in Unity 2021.3 and above that the version 3 didn't work. Downgraded to version 2 worked perfectly.

Just hope that this wonderful library can be used inside Unity editor.

**Comment by robertvazan** [comment]
Just use version 2 then. Features in version 3 would not work on .NET Standard anyway. Unity has [plans](https://visualstudiomagazine.com/articles/2021/04/22/unity-plans.aspx) for supporting .NET 6, so fingers crossed.
