### ISSUE TITLE
[Question] Burst and iBurst available?

### ISSUE THREAD

**Issue by morph13nd** [robertvazan/guerrillantp#4]
Is there burst or iburst support as of now or in the development pipeline? I love this project thus far. Thank you.

**Comment by robertvazan** [comment]
Not implemented and not planned yet. Seems useful, so if you have a patch, send in a pull request.

**Comment by morph13nd** [comment]
I will leave this to a more capable programmer. Thank you for the response!

**Comment by DamianMorozov** [comment]
> I will leave this to a more capable programmer. Thank you for the response!
It is not the NtpClient's issue. Just your's.

**Comment by robertvazan** [comment]
GuerrillaNtp is a minimal embeddable SNTP client. Built-in burst functionality is not a good fit for it. Every application using the library is likely to have different synchronization strategy. If you need burst in your application, you can implement it in a few lines using current GuerrillaNtp API.
